name: Sync

on:
  push:
    branches: [main, master]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@master # 将代码拷贝到虚机中

      - name: buildAndDeploy
        uses: JamesIves/github-pages-deploy-action@master 
        env:
          ACCESS_TOKEN: ${{ secrets.BLUE_CORAL_CLIENT_TOKEN }} # 使用刚新建的secret
          BRANCH: gh-pages # 存放产物的分支名称
          FOLDER: dist # 存放build后产物的目录
          BUILD_SCRIPT: npm install && npm run build # 执行的命令
          
      - name: Sync to Gitee
        uses: wearerequired/git-mirror-action@master
        env:
          # 注意在 Settings->Secrets 配置 GITEE_RSA_PRIVATE_KEY
          SSH_PRIVATE_KEY: ${{ secrets.GITEE_RSA_PRIVATE_KEY }}
        with:
          # 注意替换为你的 GitHub 源仓库地址
          source-repo: git@github.com:mrTangYun/genealogy-client.git
          # 注意替换为你的 Gitee 目标仓库地址
          destination-repo: git@gitee.com:github-20735959/genealogy-client.git

      - name: Build Gitee Pages
        uses: yanglbme/gitee-pages-action@main
        with:
          # 注意替换为你的 Gitee 用户名
          gitee-username: github-20735959
          # 注意在 Settings->Secrets 配置 GITEE_PASSWORD
          gitee-password: ${{ secrets.GITEE_PASSWORD }}
          # 注意替换为你的 Gitee 仓库，仓库名严格区分大小写，请准确填写，否则会出错
          gitee-repo: doocs/advanced-java
          # 要部署的分支，默认是 master，若是其他分支，则需要指定（指定的分支必须存在）
          branch: main